"""Added unique constraints to employees and customers tables

Revision ID: 90ed610740b7
Revises: d82cecf1d621
Create Date: 2024-12-30 20:09:24.387102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90ed610740b7'
down_revision: Union[str, None] = 'd82cecf1d621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['email'])
    op.create_unique_constraint(None, 'customers', ['phone_number'])
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_unique_constraint(None, 'employees', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
