"""Add hashed_password to Employee

Revision ID: 96c2f158e3d6
Revises: 90ed610740b7
Create Date: 2025-04-02 14:53:56.149569

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c2f158e3d6'
down_revision: Union[str, None] = '90ed610740b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hashed_password', sa.String(), nullable=True))
    op.alter_column('orders', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'is_returned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'is_returned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
